# base configuration
train_bc: 2
eval_bc: 8
num_epochs: 50

img_sz: [512, 512]
val_length: 1000
stable_path: '/pretrained_model/stable_diffusion'
control_net_path: '/pretrained_model/controlnet'


# train process configuration
val_inter: 3
save_inter: 5

# pretrained vae
target_path: '/pretrained_model/stable_diffusion/vae'


# model configuration
unet_resume: '/pretrained_model/stable_diffusion/unet'
sample_size: 64
in_channels: 4
out_channels: 4
layers_per_block: 2
block_out_channels: [320, 640, 1280, 1280]
down_block_types: [
    "CrossAttnDownBlock2D",
    "CrossAttnDownBlock2D",
    "CrossAttnDownBlock2D",
    "DownBlock2D"
  ]
#   ["DownBlock2D",  "DownBlock2D", "DownBlock2D",
# "DownBlock2D", "AttnDownBlock2D",  "DownBlock2D"]
up_block_types: [
    "UpBlock2D",
    "CrossAttnUpBlock2D",
    "CrossAttnUpBlock2D",
    "CrossAttnUpBlock2D"
  ]

cross_attention_dim: 768

num_train_timesteps: 1000
lr: 0.0001

# accelerate config
split_batches: False
mixed_precision: 'fp16'
log_with: 'tensorboard'
gradient_accumulation_steps: 4
project_dir: '/finetune/weights/exp_5'