# base configuration
train_bc: 8
eval_bc: 16
num_epochs: 200
image_title: 'diffusion'
train_path: '/home/fanzhaojiehd/advanced_VT/dataset/data_sloeaffa'
val_path: '/home/fanzhaojiehd/city_improved/dataset/edges2shoes/val'

# train process configuration
val_inter: 10
save_inter: 40

# model configuration
sample_size: 256
in_channels: 3
out_channels: 3
layers_per_block: 2
block_out_channels: [128, 128, 256, 256, 512, 512]
down_block_types: ["DownBlock2D",  "DownBlock2D", "DownBlock2D",
            "DownBlock2D", "AttnDownBlock2D",  "DownBlock2D"]
up_block_types: ["UpBlock2D",  "AttnUpBlock2D", "UpBlock2D", 
                "UpBlock2D", "UpBlock2D", "UpBlock2D",]

num_train_timesteps: 1000
lr: 0.0001
            
# accelerate config
split_batches: False
mixed_precision: 'fp16'
log_with: "tensorboard"
project_dir: 'weights/exp_11_4'
